#!/bin/bash

let file

# if there's no argument, use the first (and hopefully only!) implementation (.cpp) found.
if [ -z $1 ]; then
    file=$(echo *.cpp | cut -d ' ' -f1)
else
    file=$1
fi

# uncomment the last line, which should be a one liner main function that runs test()
# (osx idiom for sed in-place)
sed -i '' '$s/\/\/\(.*$\)/\1/' $file

# compile the 1st command line argument $1 to a.out
clang++ -std=c++17 -stdlib=libc++ -I/usr/local/opt/qt/include $file

# comment the last line, which should be a one liner main function that runs test()
sed -i '' '$s/^.*$/\/\/&/' $file

# run the output file with all the original command line arguments starting at $2
./a.out `echo ${@:2}`

rm -f a.out
