#!/bin/bash

./trello_auth

source brand_trello_cards

# card id for brand
brand=$1

 foxList=$(./get_card "${cards[$brand]}" | jq '.idList' | tr -d \")
 ./get_list "$foxList" | jq '.name' | tr -d \"
