#!/bin/bash

source trello_auth_creds

args='{}'

for ((i=1; i<=$#; i++)); do
    case "${!i}" in
        --args)
            j=$((i+1))
            arg="${!j}"
            while [ "${arg:1}" != '-' ] && [ "$j" -le "$#" ]; do
                pair=${!j} # e.g. foo=bar
                argName=${pair%=*} # foo
                argValue=${pair#*=} # bar
                args=$(echo $args | jq ".$argName=\"$argValue\"") # {...,{foo: bar}}
                j=$((j+1))
                arg="${!j}"
            done
            i=$((j-1))
            ;;
        --endpoint)
            ((i++))
            endpoint=${!i}
            ;;
        --method)
            ((i++))
            method=${!i}
            ;;
        *)
            echo "Usage [ --args name1=value1 [name2=value2 ...] | --endpoint lists/{id} | --method (GET|POST|...) ]."
            exit 1
    esac
done
url="https://api.trello.com/1/$endpoint?key=$TRELLO_API_KEY&token=$TRELLO_API_TOKEN"
curl -H "Content-Type: application/json" -X "$method" -d "$args" "$url" 
