#!/bin/bash

source trello_auth_creds

# named args

usageStr="
Usage: ./$0 [
    --args name1=value1 name2=value2 ... |
    --endpoint lists/{id} |
    --method {GET|POST|...}
].
"

if [ $# -lt 2 ]; then 
    echo "$usageStr" && exit 1
fi

args='{}'
for ((i=1; i<=$#; i++)); do
    case "${!i}" in
        --args)
            j=$((i+1))
            arg="${!j}"
            while [ "${arg::1}" != '-' ] && [ "$j" -le "$#" ]; do
                pair=${!j} # e.g. foo=bar
                argName=${pair%=*} # foo
                argValue=${pair#*=} # bar
                args=$(echo $args | jq ".$argName=\"$argValue\"") # {...,{foo: bar}}
                j=$((j+1))
                arg="${!j}"
            done
            i=$((j-1))
            ;;
        --endpoint)
            ((i++))
            endpoint=${!i}
            ;;
        --method)
            ((i++))
            method=${!i}
            ;;
        *)
            echo "$usageStr" && exit 1
    esac
done

url="https://api.trello.com/1/$endpoint?key=$TRELLO_API_KEY&token=$TRELLO_API_TOKEN"

curl --silent --show-error -H "Content-Type: application/json" -X "$method" -d "$args" "$url" 
