#!/bin/bash

# init named args map
declare -A args=( 
    [brand]="" 
    [cardId]="" 
    [boardId]="" 
    [newListId]="" 
    [approvedReadyToUpdateLabelId]="" 
    [s3LogDir]=""
    [awsProfile]=""
)
# fill named args
for ((i=1; i<=$#; i++)); do
   match=""
   for it in "${!args[@]}"; do
       if [ "--$it" == "${!i}" ]; then
           ((i++))
           args[$it]=${!i}
           match=1
       fi
   done
   if [ -z $match ]; then
       i=1
       for ((; i < ${#args[@]}; i++)); do
           usageStr+="--${!i} <${!i}> | "
       done
       usageStr+="--${!i} <${!i}>" #last
       echo "Usage: $usageStr"
       exit 1
   fi
done

# named args already checked for null in async_updates, no need to do it here again

log="./logs.d/${args[brand]}.log"
touch $log
chmod u+rw $log
s3Log="${args[s3LogDir]}/${args[brand]}.log"

if ./mock_update_script "${args[brand]}" > $log; then
    # update success
    {
        ./move_card "${args[cardId]}" "${args[boardId]}" "${args[newListId]}"
        ./remove_label_from_card "${args[cardId]}" "${args[approvedReadyForUpdateLabelId]}"
    } > $log
    #...
else
    # update fail
    echo "UPDATE FAIL ${args[brand]}"
    echo "AWS S3 URI: $s3Log"
fi

# copy log to s3
aws s3 cp $log $s3Log
