#!/bin/bash

# Enable job control (not required on macOS).
set -m

printReport() {
    echo "task id: $i | wait time: $2"
}

executeTask() {
    rand=$((1 + RANDOM % 10))
    sleep $rand
    printReport "$1" "$rand"
}

# Execute 25 tasks asynchronously. Each task sleeps 1-10 seconds 
# pseudo-randomly before printing a report.
for i in $(seq 25); do
    executeTask "$i" &
done

# Await completion of all 25 asynchronous tasks.
wait
