#!/bin/bash

touch new_script_with_named_args
f=new_script_with_named_args

{ # print beginning of for loop and case statement to file
    echo 'for ((i=1; i<=$#; i++)); do'
    echo '   case "${!i}" in'
}>>$f
        
# for each arg print a case
for it in "$@"; do 
    { # print to file
        echo "       --$it)"
        echo '           ((i++)); '"$it"'=${!i}'
        echo '           ;;'
    }>>$f
done

# print the usage and end of case statement and for loop

usageStr=''
# append all but the last one
i=1
for ((; i < $#; i++)); do
    usageStr+="--${!i} <${!i}> | "
done
# append last one
usageStr+="--${!i} <${!i}>"

{ # print to file
    echo '       *)'
    echo "           echo \"Usage: $usageStr\""
    echo '           exit 1'
    echo '   esac'
    echo 'done'
}>>$f

# print file to stdout
cat $f
# might not need to redirect this but just to be safe
rm $f > /dev/null
